//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: solana_program
// ----------------------------------------------------------------------------
pub mod solana_program {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for solana_program
    pub fn program_id() -> Pubkey {
        pubkey!("8M5yieUh7pxwUi1YBByDF82nqoorZwaKi8dBoMVpurFa")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: Cancel
    // ....................................................................

    /// Main instruction struct for Cancel
    pub struct CancelInstruction {
        pub accounts: CancelInstructionAccountMetas,
        pub data: CancelInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Cancel instruction
    #[derive(Debug, Clone, Default)]
    pub struct CancelInstructionAccountMetas {
        pub creator: AccountMeta,

        pub mint: AccountMeta,

        pub stream: AccountMeta,

        pub vault: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub recipient_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Cancel instruction
    #[derive(Debug, Clone)]
    pub struct CancelInstructionAccounts {
        pub creator: Pubkey,

        pub mint: Pubkey,

        pub stream: Pubkey,

        pub vault: Pubkey,

        pub creator_token_account: Pubkey,

        pub recipient_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl CancelInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            mint: Pubkey,

            stream: Pubkey,

            vault: Pubkey,

            creator_token_account: Pubkey,

            recipient_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                creator,

                mint,

                stream,

                vault,

                creator_token_account,

                recipient_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for Cancel
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CancelInstructionData {}

    impl CancelInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CancelInstruction
    impl CancelInstruction {
        fn discriminator() -> [u8; 8] {
            [232u8, 219u8, 223u8, 41u8, 219u8, 236u8, 220u8, 190u8]
        }

        pub fn data(data: CancelInstructionData) -> Self {
            Self {
                accounts: CancelInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CancelInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.recipient_token_account =
                AccountMeta::new(accounts.recipient_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.recipient_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CreateStream
    // ....................................................................

    /// Main instruction struct for CreateStream
    pub struct CreateStreamInstruction {
        pub accounts: CreateStreamInstructionAccountMetas,
        pub data: CreateStreamInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CreateStream instruction
    #[derive(Debug, Clone, Default)]
    pub struct CreateStreamInstructionAccountMetas {
        pub creator: AccountMeta,

        pub recipient: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub stream: AccountMeta,

        pub vault: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub system_program: AccountMeta,

        pub token_program: AccountMeta,

        pub associated_token_program: AccountMeta,
    }

    /// Account pubkeys for CreateStream instruction
    #[derive(Debug, Clone)]
    pub struct CreateStreamInstructionAccounts {
        pub creator: Pubkey,

        pub recipient: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,

        pub stream: Pubkey,

        pub vault: Pubkey,

        pub creator_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl CreateStreamInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            recipient: Pubkey,

            mint: Pubkey,

            config: Pubkey,

            stream: Pubkey,

            vault: Pubkey,

            creator_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                creator,

                recipient,

                mint,

                config,

                stream,

                vault,

                creator_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for CreateStream
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CreateStreamInstructionData {
        pub amount: u64,

        pub start_ts: i64,

        pub cliff_ts: i64,

        pub end_ts: i64,

        pub vesting_type: u8,

        pub milestones: Vec<MilestoneInput>,

        pub nonce: u64,
    }

    impl CreateStreamInstructionData {
        pub fn new(
            amount: u64,

            start_ts: i64,

            cliff_ts: i64,

            end_ts: i64,

            vesting_type: u8,

            milestones: Vec<MilestoneInput>,

            nonce: u64,
        ) -> Self {
            Self {
                amount,

                start_ts,

                cliff_ts,

                end_ts,

                vesting_type,

                milestones,

                nonce,
            }
        }
    }

    /// Implementation for CreateStreamInstruction
    impl CreateStreamInstruction {
        fn discriminator() -> [u8; 8] {
            [71u8, 188u8, 111u8, 127u8, 108u8, 40u8, 229u8, 158u8]
        }

        pub fn data(data: CreateStreamInstructionData) -> Self {
            Self {
                accounts: CreateStreamInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CreateStreamInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.recipient = AccountMeta::new_readonly(accounts.recipient, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.associated_token_program = AccountMeta::new_readonly(
                pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
                false,
            );

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.system_program.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.associated_token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: EditCliff
    // ....................................................................

    /// Main instruction struct for EditCliff
    pub struct EditCliffInstruction {
        pub accounts: EditCliffInstructionAccountMetas,
        pub data: EditCliffInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for EditCliff instruction
    #[derive(Debug, Clone, Default)]
    pub struct EditCliffInstructionAccountMetas {
        pub creator: AccountMeta,

        pub stream: AccountMeta,
    }

    /// Account pubkeys for EditCliff instruction
    #[derive(Debug, Clone)]
    pub struct EditCliffInstructionAccounts {
        pub creator: Pubkey,

        pub stream: Pubkey,
    }

    impl EditCliffInstructionAccounts {
        pub fn new(creator: Pubkey, stream: Pubkey) -> Self {
            Self { creator, stream }
        }
    }

    /// Instruction data for EditCliff
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct EditCliffInstructionData {
        pub new_cliff_ts: i64,
    }

    impl EditCliffInstructionData {
        pub fn new(new_cliff_ts: i64) -> Self {
            Self { new_cliff_ts }
        }
    }

    /// Implementation for EditCliffInstruction
    impl EditCliffInstruction {
        fn discriminator() -> [u8; 8] {
            [41u8, 203u8, 122u8, 7u8, 21u8, 225u8, 162u8, 98u8]
        }

        pub fn data(data: EditCliffInstructionData) -> Self {
            Self {
                accounts: EditCliffInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: EditCliffInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.stream.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: EditLinear
    // ....................................................................

    /// Main instruction struct for EditLinear
    pub struct EditLinearInstruction {
        pub accounts: EditLinearInstructionAccountMetas,
        pub data: EditLinearInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for EditLinear instruction
    #[derive(Debug, Clone, Default)]
    pub struct EditLinearInstructionAccountMetas {
        pub creator: AccountMeta,

        pub mint: AccountMeta,

        pub stream: AccountMeta,

        pub vault: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for EditLinear instruction
    #[derive(Debug, Clone)]
    pub struct EditLinearInstructionAccounts {
        pub creator: Pubkey,

        pub mint: Pubkey,

        pub stream: Pubkey,

        pub vault: Pubkey,

        pub creator_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl EditLinearInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            mint: Pubkey,

            stream: Pubkey,

            vault: Pubkey,

            creator_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                creator,

                mint,

                stream,

                vault,

                creator_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for EditLinear
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct EditLinearInstructionData {
        pub new_end_ts: i64,

        pub topup_amount: u64,
    }

    impl EditLinearInstructionData {
        pub fn new(new_end_ts: i64, topup_amount: u64) -> Self {
            Self {
                new_end_ts,

                topup_amount,
            }
        }
    }

    /// Implementation for EditLinearInstruction
    impl EditLinearInstruction {
        fn discriminator() -> [u8; 8] {
            [255u8, 42u8, 53u8, 36u8, 79u8, 96u8, 83u8, 223u8]
        }

        pub fn data(data: EditLinearInstructionData) -> Self {
            Self {
                accounts: EditLinearInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: EditLinearInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: EditMilestone
    // ....................................................................

    /// Main instruction struct for EditMilestone
    pub struct EditMilestoneInstruction {
        pub accounts: EditMilestoneInstructionAccountMetas,
        pub data: EditMilestoneInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for EditMilestone instruction
    #[derive(Debug, Clone, Default)]
    pub struct EditMilestoneInstructionAccountMetas {
        pub creator: AccountMeta,

        pub stream: AccountMeta,

        pub milestone: AccountMeta,

        pub mint: AccountMeta,

        pub vault: AccountMeta,

        pub creator_token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for EditMilestone instruction
    #[derive(Debug, Clone)]
    pub struct EditMilestoneInstructionAccounts {
        pub creator: Pubkey,

        pub stream: Pubkey,

        pub milestone: Pubkey,

        pub mint: Pubkey,

        pub vault: Pubkey,

        pub creator_token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl EditMilestoneInstructionAccounts {
        pub fn new(
            creator: Pubkey,

            stream: Pubkey,

            milestone: Pubkey,

            mint: Pubkey,

            vault: Pubkey,

            creator_token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                creator,

                stream,

                milestone,

                mint,

                vault,

                creator_token_account,

                token_program,
            }
        }
    }

    /// Instruction data for EditMilestone
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct EditMilestoneInstructionData {
        pub new_amount: u64,
    }

    impl EditMilestoneInstructionData {
        pub fn new(new_amount: u64) -> Self {
            Self { new_amount }
        }
    }

    /// Implementation for EditMilestoneInstruction
    impl EditMilestoneInstruction {
        fn discriminator() -> [u8; 8] {
            [123u8, 218u8, 165u8, 226u8, 209u8, 227u8, 8u8, 166u8]
        }

        pub fn data(data: EditMilestoneInstructionData) -> Self {
            Self {
                accounts: EditMilestoneInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: EditMilestoneInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.milestone = AccountMeta::new(accounts.milestone, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.creator_token_account =
                AccountMeta::new(accounts.creator_token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.milestone.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.creator_token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeConfig
    // ....................................................................

    /// Main instruction struct for InitializeConfig
    pub struct InitializeConfigInstruction {
        pub accounts: InitializeConfigInstructionAccountMetas,
        pub data: InitializeConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeConfigInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeConfig instruction
    #[derive(Debug, Clone)]
    pub struct InitializeConfigInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,
    }

    impl InitializeConfigInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey) -> Self {
            Self { admin, config }
        }
    }

    /// Instruction data for InitializeConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeConfigInstructionData {}

    impl InitializeConfigInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeConfigInstruction
    impl InitializeConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [208u8, 127u8, 21u8, 1u8, 194u8, 190u8, 196u8, 70u8]
        }

        pub fn data(data: InitializeConfigInstructionData) -> Self {
            Self {
                accounts: InitializeConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeConfigInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UnlockMilestone
    // ....................................................................

    /// Main instruction struct for UnlockMilestone
    pub struct UnlockMilestoneInstruction {
        pub accounts: UnlockMilestoneInstructionAccountMetas,
        pub data: UnlockMilestoneInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UnlockMilestone instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnlockMilestoneInstructionAccountMetas {
        pub creator: AccountMeta,

        pub stream: AccountMeta,

        pub milestone: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UnlockMilestone instruction
    #[derive(Debug, Clone)]
    pub struct UnlockMilestoneInstructionAccounts {
        pub creator: Pubkey,

        pub stream: Pubkey,

        pub milestone: Pubkey,
    }

    impl UnlockMilestoneInstructionAccounts {
        pub fn new(creator: Pubkey, stream: Pubkey, milestone: Pubkey) -> Self {
            Self {
                creator,

                stream,

                milestone,
            }
        }
    }

    /// Instruction data for UnlockMilestone
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnlockMilestoneInstructionData {}

    impl UnlockMilestoneInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnlockMilestoneInstruction
    impl UnlockMilestoneInstruction {
        fn discriminator() -> [u8; 8] {
            [131u8, 196u8, 6u8, 134u8, 153u8, 130u8, 248u8, 238u8]
        }

        pub fn data(data: UnlockMilestoneInstructionData) -> Self {
            Self {
                accounts: UnlockMilestoneInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnlockMilestoneInstructionAccounts) -> Self {
            self.accounts.creator = AccountMeta::new(accounts.creator, true);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.milestone = AccountMeta::new(accounts.milestone, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.creator.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.milestone.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Withdraw
    // ....................................................................

    /// Main instruction struct for Withdraw
    pub struct WithdrawInstruction {
        pub accounts: WithdrawInstructionAccountMetas,
        pub data: WithdrawInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Withdraw instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawInstructionAccountMetas {
        pub recipient: AccountMeta,

        pub mint: AccountMeta,

        pub config: AccountMeta,

        pub stream: AccountMeta,

        pub vault: AccountMeta,

        pub recipient_ata: AccountMeta,

        pub fee_vault: AccountMeta,

        pub chainlink_feed: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Withdraw instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawInstructionAccounts {
        pub recipient: Pubkey,

        pub mint: Pubkey,

        pub config: Pubkey,

        pub stream: Pubkey,

        pub vault: Pubkey,

        pub recipient_ata: Pubkey,

        pub fee_vault: Pubkey,

        pub chainlink_feed: Pubkey,

        pub token_program: Pubkey,
    }

    impl WithdrawInstructionAccounts {
        pub fn new(
            recipient: Pubkey,

            mint: Pubkey,

            config: Pubkey,

            stream: Pubkey,

            vault: Pubkey,

            recipient_ata: Pubkey,

            fee_vault: Pubkey,

            chainlink_feed: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                recipient,

                mint,

                config,

                stream,

                vault,

                recipient_ata,

                fee_vault,

                chainlink_feed,

                token_program,
            }
        }
    }

    /// Instruction data for Withdraw
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawInstructionData {}

    impl WithdrawInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for WithdrawInstruction
    impl WithdrawInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 18u8, 70u8, 156u8, 148u8, 109u8, 161u8, 34u8]
        }

        pub fn data(data: WithdrawInstructionData) -> Self {
            Self {
                accounts: WithdrawInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawInstructionAccounts) -> Self {
            self.accounts.recipient = AccountMeta::new(accounts.recipient, true);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.stream = AccountMeta::new(accounts.stream, false);

            self.accounts.vault = AccountMeta::new(accounts.vault, false);

            self.accounts.recipient_ata = AccountMeta::new(accounts.recipient_ata, false);

            self.accounts.fee_vault = AccountMeta::new(accounts.fee_vault, false);

            self.accounts.chainlink_feed =
                AccountMeta::new_readonly(accounts.chainlink_feed, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.recipient.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.stream.clone());

            metas.push(self.accounts.vault.clone());

            metas.push(self.accounts.recipient_ata.clone());

            metas.push(self.accounts.fee_vault.clone());

            metas.push(self.accounts.chainlink_feed.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: CliffEdited
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct CliffEdited {
    pub stream: Pubkey,

    pub old_cliff_ts: i64,

    pub new_cliff_ts: i64,

    pub timestamp: i64,
}

impl CliffEdited {
    pub fn new(stream: Pubkey, old_cliff_ts: i64, new_cliff_ts: i64, timestamp: i64) -> Self {
        Self {
            stream,

            old_cliff_ts,

            new_cliff_ts,

            timestamp,
        }
    }
}

/// Custom struct: ConfigAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ConfigAccount {
    pub admin_authority: Pubkey,

    pub fee_authority: Pubkey,

    pub paused: bool,

    pub withdraw_fee_bps: u16,

    pub max_withdraw_fee_bps: u16,

    pub fee_change_timelock_seconds: u64,

    pub pending_fees: Option<PendingFees>,

    pub allowed_mints: Vec<Pubkey>,

    pub bump: u8,
}

impl ConfigAccount {
    pub fn new(
        admin_authority: Pubkey,

        fee_authority: Pubkey,

        paused: bool,

        withdraw_fee_bps: u16,

        max_withdraw_fee_bps: u16,

        fee_change_timelock_seconds: u64,

        pending_fees: Option<PendingFees>,

        allowed_mints: Vec<Pubkey>,

        bump: u8,
    ) -> Self {
        Self {
            admin_authority,

            fee_authority,

            paused,

            withdraw_fee_bps,

            max_withdraw_fee_bps,

            fee_change_timelock_seconds,

            pending_fees,

            allowed_mints,

            bump,
        }
    }
}

/// Custom struct: LinearEdited
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct LinearEdited {
    pub stream: Pubkey,

    pub old_end_ts: i64,

    pub new_end_ts: i64,

    pub old_total_amount: u64,

    pub new_total_amount: u64,

    pub topup_amount: u64,

    pub timestamp: i64,
}

impl LinearEdited {
    pub fn new(
        stream: Pubkey,

        old_end_ts: i64,

        new_end_ts: i64,

        old_total_amount: u64,

        new_total_amount: u64,

        topup_amount: u64,

        timestamp: i64,
    ) -> Self {
        Self {
            stream,

            old_end_ts,

            new_end_ts,

            old_total_amount,

            new_total_amount,

            topup_amount,

            timestamp,
        }
    }
}

/// Custom struct: MilestoneAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MilestoneAccount {
    pub stream: Pubkey,

    pub index: u8,

    pub unlock_ts: i64,

    pub amount: u64,

    pub approved: bool,

    pub unlocked: bool,

    pub bump: u8,
}

impl MilestoneAccount {
    pub fn new(
        stream: Pubkey,

        index: u8,

        unlock_ts: i64,

        amount: u64,

        approved: bool,

        unlocked: bool,

        bump: u8,
    ) -> Self {
        Self {
            stream,

            index,

            unlock_ts,

            amount,

            approved,

            unlocked,

            bump,
        }
    }
}

/// Custom struct: MilestoneEdited
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MilestoneEdited {
    pub stream: Pubkey,

    pub milestone: Pubkey,

    pub index: u8,

    pub old_amount: u64,

    pub new_amount: u64,

    pub timestamp: i64,
}

impl MilestoneEdited {
    pub fn new(
        stream: Pubkey,

        milestone: Pubkey,

        index: u8,

        old_amount: u64,

        new_amount: u64,

        timestamp: i64,
    ) -> Self {
        Self {
            stream,

            milestone,

            index,

            old_amount,

            new_amount,

            timestamp,
        }
    }
}

/// Custom struct: MilestoneInput
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MilestoneInput {
    pub amount: u64,
}

impl MilestoneInput {
    pub fn new(amount: u64) -> Self {
        Self { amount }
    }
}

/// Custom struct: MilestoneUnlocked
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct MilestoneUnlocked {
    pub stream: Pubkey,

    pub milestone: Pubkey,

    pub index: u8,

    pub amount: u64,

    pub unlock_ts: i64,
}

impl MilestoneUnlocked {
    pub fn new(stream: Pubkey, milestone: Pubkey, index: u8, amount: u64, unlock_ts: i64) -> Self {
        Self {
            stream,

            milestone,

            index,

            amount,

            unlock_ts,
        }
    }
}

/// Custom struct: PendingFees
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PendingFees {
    pub new_withdraw_fee_bps: u16,

    pub effective_at: i64,
}

impl PendingFees {
    pub fn new(new_withdraw_fee_bps: u16, effective_at: i64) -> Self {
        Self {
            new_withdraw_fee_bps,

            effective_at,
        }
    }
}

/// Custom struct: StreamAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StreamAccount {
    pub creator: Pubkey,

    pub recipient: Pubkey,

    pub mint: Pubkey,

    pub vault: Pubkey,

    pub total_amount: u64,

    pub withdrawn: u64,

    pub start_ts: i64,

    pub cliff_ts: i64,

    pub end_ts: i64,

    pub vesting_type: u8,

    pub status: u8,

    pub cancelable: bool,

    pub milestone_count: u8,

    pub next_milestone_index: u8,

    pub cancelled: bool,

    pub nonce: u64,

    pub bump: u8,

    pub unlocked_milestone_amount: u64,
}

impl StreamAccount {
    pub fn new(
        creator: Pubkey,

        recipient: Pubkey,

        mint: Pubkey,

        vault: Pubkey,

        total_amount: u64,

        withdrawn: u64,

        start_ts: i64,

        cliff_ts: i64,

        end_ts: i64,

        vesting_type: u8,

        status: u8,

        cancelable: bool,

        milestone_count: u8,

        next_milestone_index: u8,

        cancelled: bool,

        nonce: u64,

        bump: u8,

        unlocked_milestone_amount: u64,
    ) -> Self {
        Self {
            creator,

            recipient,

            mint,

            vault,

            total_amount,

            withdrawn,

            start_ts,

            cliff_ts,

            end_ts,

            vesting_type,

            status,

            cancelable,

            milestone_count,

            next_milestone_index,

            cancelled,

            nonce,

            bump,

            unlocked_milestone_amount,
        }
    }
}

/// Custom struct: StreamCancelled
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StreamCancelled {
    pub stream: Pubkey,

    pub creator: Pubkey,

    pub recipient: Pubkey,

    pub vested_amount: u64,

    pub returned_to_creator: u64,

    pub claimable_for_recipient: u64,

    pub timestamp: i64,
}

impl StreamCancelled {
    pub fn new(
        stream: Pubkey,

        creator: Pubkey,

        recipient: Pubkey,

        vested_amount: u64,

        returned_to_creator: u64,

        claimable_for_recipient: u64,

        timestamp: i64,
    ) -> Self {
        Self {
            stream,

            creator,

            recipient,

            vested_amount,

            returned_to_creator,

            claimable_for_recipient,

            timestamp,
        }
    }
}

/// Custom struct: StreamCreated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StreamCreated {
    pub stream: Pubkey,

    pub creator: Pubkey,

    pub recipient: Pubkey,

    pub mint: Pubkey,

    pub vault: Pubkey,

    pub total_amount: u64,

    pub vesting_type: u8,

    pub start_ts: i64,

    pub cliff_ts: i64,

    pub end_ts: i64,

    pub milestone_count: u8,

    pub cancelable: bool,

    pub nonce: u64,

    pub created_at: i64,
}

impl StreamCreated {
    pub fn new(
        stream: Pubkey,

        creator: Pubkey,

        recipient: Pubkey,

        mint: Pubkey,

        vault: Pubkey,

        total_amount: u64,

        vesting_type: u8,

        start_ts: i64,

        cliff_ts: i64,

        end_ts: i64,

        milestone_count: u8,

        cancelable: bool,

        nonce: u64,

        created_at: i64,
    ) -> Self {
        Self {
            stream,

            creator,

            recipient,

            mint,

            vault,

            total_amount,

            vesting_type,

            start_ts,

            cliff_ts,

            end_ts,

            milestone_count,

            cancelable,

            nonce,

            created_at,
        }
    }
}

/// Custom struct: TokensClaimed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensClaimed {
    pub stream: Pubkey,

    pub recipient: Pubkey,

    pub mint: Pubkey,

    pub claimable: u64,

    pub fee_lamports: u64,

    pub withdrawn_total: u64,

    pub timestamp: i64,
}

impl TokensClaimed {
    pub fn new(
        stream: Pubkey,

        recipient: Pubkey,

        mint: Pubkey,

        claimable: u64,

        fee_lamports: u64,

        withdrawn_total: u64,

        timestamp: i64,
    ) -> Self {
        Self {
            stream,

            recipient,

            mint,

            claimable,

            fee_lamports,

            withdrawn_total,

            timestamp,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
