name: Solana Program - Anchor Tests

on:
  push:
    branches: [main]
    paths:
      - "programs/**"
      - "tests/**"
      - "Anchor.toml"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: [main]
    paths:
      - "programs/**"
      - "tests/**"
      - "Anchor.toml"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:
    inputs:
      program:
        description: "Program to test"
        required: true
        default: "unified-flow"

jobs:
  test:
    uses: solana-developers/github-workflows/.github/workflows/test.yaml@v0.4.0
    with:
      program: ${{ 'unified-flow' }}
